[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "your_project_name"
version = "0.1.0"
dependencies = [
    # List your project's dependencies here, e.g.
    # "some_package >= 1.0",
]
